# Generated by Django 3.0.6 on 2020-05-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceno', models.CharField(max_length=200)),
                ('transtype', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('ticket', models.CharField(max_length=200)),
                ('externalno', models.CharField(max_length=200)),
                ('cctname', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('sordescription', models.TextField()),
                ('qty', models.CharField(max_length=200)),
                ('rate', models.CharField(max_length=200)),
                ('gst', models.CharField(max_length=200)),
                ('total', models.CharField(max_length=200)),
                ('notes', models.TextField(null=True)),
                ('status', models.BooleanField(null=True, verbose_name='Charge valid')),
                ('reversed', models.BooleanField(null=True, verbose_name='Charged Reversed')),
            ],
        ),
    ]
