# Generated by Django 3.0.6 on 2020-05-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Towa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='gst',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='invoiceno',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='qty',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='rate',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='ticket',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='total',
            field=models.CharField(max_length=200),
        ),
    ]
