# Generated by Django 3.0.6 on 2020-05-20 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Towa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='reversed',
            field=models.BooleanField(null=True, verbose_name='Charged Back is Reversed'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.BooleanField(null=True, verbose_name='Is Charge back valid'),
        ),
    ]
